// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeUserService() *UserService {
	config := NewConfig()
	database := NewDatabase(config)
	userRepository := NewUserRepository(database)
	cache := NewCache(config)
	userService := NewUserService(userRepository, cache)
	return userService
}

// wire.go:

var ConfigSet = wire.NewSet(NewConfig)

var DatabaseSet = wire.NewSet(NewDatabase, NewCache)

var RepositorySet = wire.NewSet(NewUserRepository)

var ServiceSet = wire.NewSet(NewUserService)

var AppSet = wire.NewSet(
	ConfigSet,
	DatabaseSet,
	RepositorySet,
	ServiceSet,
)
