package resolverfn

// This file will be automatically regenerated based on the schema, any resolver
// implementations will be copied through when generating and any unknown code
// will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"graphql-demo/graph/model"
	dbmodel "graphql-demo/internal/model"
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	var dbUsers []dbmodel.User
	if err := r.DB.Preload("Tasks").Find(&dbUsers).Error; err != nil {
		return nil, fmt.Errorf("kullanıcılar alınamadı: %w", err)
	}

	users := make([]*model.User, len(dbUsers))
	for i := range dbUsers {
		users[i] = dbUserToGraphQL(&dbUsers[i])
	}

	return users, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	userID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("geçersiz ID: %s", id)
	}

	var dbUser dbmodel.User
	if err := r.DB.Preload("Tasks").First(&dbUser, userID).Error; err != nil {
		return nil, fmt.Errorf("kullanıcı bulunamadı: %s", id)
	}

	return dbUserToGraphQL(&dbUser), nil
}

// Helper: DB User -> GraphQL User dönüşümü
func dbUserToGraphQL(u *dbmodel.User) *model.User {
	createdAt := u.CreatedAt
	updatedAt := u.UpdatedAt

	// User'ın task'larını dönüştür
	tasks := make([]*model.Task, len(u.Tasks))
	for i := range u.Tasks {
		tasks[i] = dbTaskToGraphQL(&u.Tasks[i])
	}

	return &model.User{
		ID:        strconv.FormatUint(uint64(u.ID), 10),
		Email:     u.Email,
		Name:      u.Name,
		CreatedAt: userTimePtr(createdAt),
		UpdatedAt: userTimePtr(updatedAt),
		Tasks:     tasks,
	}
}

func userTimePtr(t time.Time) *time.Time {
	return &t
}
