version: '3'

tasks:
  dev:
    desc: "Air ile development server başlat"
    cmds:
      - air

  run:
    desc: "Uygulamayı çalıştır"
    cmds:
      - go run main.go

  build:
    desc: "Binary oluştur"
    cmds:
      - go build -o bin/app main.go

  test:
    desc: "Testleri çalıştır"
    cmds:
      - go test ./...

  docker:up:
    desc: "Docker servislerini başlat"
    cmds:
      - docker-compose up -d

  docker:down:
    desc: "Docker servislerini durdur"
    cmds:
      - docker-compose down

  tidy:
    desc: "Go mod tidy"
    cmds:
      - go mod tidy
